name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Dummy'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Build And Deploy
      run: |
        git config --global user.email "h.nakamura0903@gmail.com"
        git config --global user.name "nekoTheShadow"
        msg=$(git log -1 --pretty="%H %s")

        git clone --recursive -b doc    https://github.com/nekoTheShadow/qiita-backup.git public
        git clone --recursive -b backup https://github.com/nekoTheShadow/qiita-backup.git backup
        ruby script/backup.rb
        ruby script/convert.rb
        hugo --minify

        cd public
        if [[ $(git status -s | wc -l) -ne 0 ]]; then
          git add -A
          git commit -m "Commit by Github Actions (last commit: ${msg})"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nekoTheShadow/qiita-backup.git doc
        fi

        cd ..
        cd backup
        if [[ $(git status -s | wc -l) -ne 0 ]]; then
          git add -A
          git commit -m "Commit by Github Actions (last commit: ${msg})"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nekoTheShadow/qiita-backup.git backup
        fi